#!/bin/sh

is_root() {
  return $(id -u)
}

detect_system_type() {
  [ -z $system_type ] && {
    system_type=$(uname -s)
  }
}

command_exists() {
  command -v "$@" > /dev/null 2>&1
}

main() {
  detect_system_type

  ########################################
  # YADM
  ########################################
  echo "Updating the yadm repo origin URL"
  yadm remote set-url origin "git@github.com:andycarlberg/dotfiles.git"

  ########################################
  # zsh
  ########################################
  command_exists zsh && {
    [ -f ${HOME}/antigen.zsh ] || {
      curl -L git.io/antigen > antigen.zsh
    }
  }

  ########################################
  # tmux
  ########################################
  command_exists tmux && {

    [ -d "${HOME}/.tmux/plugins/tpm" ] || {
      git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    }

    ${HOME}/.tmux/plugins/tpm/bin/clean_plugins
    ${HOME}/.tmux/plugins/tpm/bin/update_plugins all
    ${HOME}/.tmux/plugins/tpm/bin/install_plugins
  }

  ########################################
  # NeoVim
  ########################################
  command_exists nvim && {
    nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
  }

}

if is_root; then
  "Don't run this as root!"
  exit 1
fi

main "$@"
