# JAVASCRIPT ------------------------------------------------------------------
[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "eslint"]
formatter = { command = 'prettier', args = ["--stdin-filepath", "file.js"] }

[[language]]
name = "jsx"
language-servers = [
  "typescript-language-server",
  "eslint"
]
formatter = { command = 'prettier', args = ["--stdin-filepath", "file.jsx"] }
# ------------------------------------------------------------------------------

# TYPESCRIPT -----------------------------------------------------------------
[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "eslint"]
formatter = { command = 'prettier', args = ["--stdin-filepath", "file.ts"] }

[[language]]
name = "tsx"
language-servers = [
  "typescript-language-server",
  "eslint"
]
formatter = { command = 'prettier', args = ["--stdin-filepath", "file.tsx"] }
# -----------------------------------------------------------------------------

# ESLint ----------------------------------------------------------------------
[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint.config]
format = true
nodePath = ""
onIgnoredFiles = "off"
packageManager = "yarn"
quiet = false
rulesCustomizations = []
run = "onType"
useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionOnSave = { mode = "all" }
experimental = {}
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }
# -------------------------------------------------------------------------------
